### ISSUE TITLE
Bugged Robbery_Actors.inc

### ISSUE THREAD

**Issue by CnRXoMoX** [PatrickGTR/gta-open#13]
When you shoot the actor while your robbing it, it spams "The store is recently robbed".

**Comment by PatrickGTR** [comment]
old include could've been used, testing required @CnRXoMoX

**Comment by CnRXoMoX** [comment]
![sa-mp-078](https://user-images.githubusercontent.com/55300557/82737203-0e9f0300-9ce4-11ea-8c10-b1528bf220ef.png)
Its a bug. Tried to install your new include. when you shot the clerk after robbed or while being rob it return 2x "The store is recently robbed."

**Comment by PatrickGTR** [comment]
solved, simple fix.
