### ISSUE TITLE
Is this 'sizeof' or 'sizof'?

### ISSUE THREAD

**Issue by StunxFS** [PatrickGTR/gta-open#43]
Hello! Great job they are doing here.

I was curious to see the source code for this and came across this:
https://github.com/PatrickGTR/gta-open/blob/769912c7601fe6c3fc2d36569fd7e7abde6a8421/gamemodes/core/houses/houses_interior-data.inc#L36

Isn't it more like a `sizeof`?

**Comment by PatrickGTR** [comment]
thank you! the function is currently not in use hence there is no warning/error flagging up.

**Comment by StunxFS** [comment]
It was nothing, that's what developers are for, to help each other

**Comment by CnRXoMoX** [comment]
Patrick probably forgot to close this, this now fixed :D
