### ISSUE TITLE
Update En-Ex instead of checkpoint

### ISSUE THREAD

**Issue by CnRXoMoX** [PatrickGTR/gta-open#48]
Use https://github.com/CnRXoMoX/X_Enex

**TODO:**

- [ ] Remove player weapons when entering the City Hall and return them when the player exits (Save to database and reset and give them back when he exits there is a call back in the readme at the repo)

- [ ] Collect entrances and interiors data

**Comment by PatrickGTR** [comment]
no need, I've completed to replicate GTA:SA default entrance.
